// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: app_upload_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*UploadAppRequest_Info
	//	*UploadAppRequest_ChunkData
	Data isUploadAppRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadAppRequest) Reset() {
	*x = UploadAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAppRequest) ProtoMessage() {}

func (x *UploadAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAppRequest.ProtoReflect.Descriptor instead.
func (*UploadAppRequest) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{0}
}

func (m *UploadAppRequest) GetData() isUploadAppRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadAppRequest) GetInfo() *AppInfo {
	if x, ok := x.GetData().(*UploadAppRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *UploadAppRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*UploadAppRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isUploadAppRequest_Data interface {
	isUploadAppRequest_Data()
}

type UploadAppRequest_Info struct {
	Info *AppInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadAppRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadAppRequest_Info) isUploadAppRequest_Data() {}

func (*UploadAppRequest_ChunkData) isUploadAppRequest_Data() {}

type AppInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName        string `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	AppDescription string `protobuf:"bytes,2,opt,name=appDescription,proto3" json:"appDescription,omitempty"`
	AppSize        string `protobuf:"bytes,3,opt,name=appSize,proto3" json:"appSize,omitempty"`
	BuildNumber    string `protobuf:"bytes,4,opt,name=buildNumber,proto3" json:"buildNumber,omitempty"`
	FileType       string `protobuf:"bytes,5,opt,name=fileType,proto3" json:"fileType,omitempty"`
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{1}
}

func (x *AppInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppInfo) GetAppDescription() string {
	if x != nil {
		return x.AppDescription
	}
	return ""
}

func (x *AppInfo) GetAppSize() string {
	if x != nil {
		return x.AppSize
	}
	return ""
}

func (x *AppInfo) GetBuildNumber() string {
	if x != nil {
		return x.BuildNumber
	}
	return ""
}

func (x *AppInfo) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string  `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size float32 `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *UploadAppResponse) Reset() {
	*x = UploadAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAppResponse) ProtoMessage() {}

func (x *UploadAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAppResponse.ProtoReflect.Descriptor instead.
func (*UploadAppResponse) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadAppResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadAppResponse) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_app_upload_service_proto protoreflect.FileDescriptor

var file_app_upload_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x66, 0x65, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6c, 0x0a, 0x10,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa3, 0x01, 0x0a, 0x07, 0x41,
	0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x70, 0x70, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x39, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x32, 0x63, 0x0a, 0x09, 0x41,
	0x70, 0x70, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x56, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x70, 0x70, 0x12, 0x22, 0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61,
	0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x65, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_app_upload_service_proto_rawDescOnce sync.Once
	file_app_upload_service_proto_rawDescData = file_app_upload_service_proto_rawDesc
)

func file_app_upload_service_proto_rawDescGZIP() []byte {
	file_app_upload_service_proto_rawDescOnce.Do(func() {
		file_app_upload_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_upload_service_proto_rawDescData)
	})
	return file_app_upload_service_proto_rawDescData
}

var file_app_upload_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_upload_service_proto_goTypes = []interface{}{
	(*UploadAppRequest)(nil),  // 0: feblic.appupload.UploadAppRequest
	(*AppInfo)(nil),           // 1: feblic.appupload.AppInfo
	(*UploadAppResponse)(nil), // 2: feblic.appupload.UploadAppResponse
}
var file_app_upload_service_proto_depIdxs = []int32{
	1, // 0: feblic.appupload.UploadAppRequest.info:type_name -> feblic.appupload.AppInfo
	0, // 1: feblic.appupload.AppUpload.UploadApp:input_type -> feblic.appupload.UploadAppRequest
	2, // 2: feblic.appupload.AppUpload.UploadApp:output_type -> feblic.appupload.UploadAppResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_upload_service_proto_init() }
func file_app_upload_service_proto_init() {
	if File_app_upload_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_upload_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_upload_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UploadAppRequest_Info)(nil),
		(*UploadAppRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_upload_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_upload_service_proto_goTypes,
		DependencyIndexes: file_app_upload_service_proto_depIdxs,
		MessageInfos:      file_app_upload_service_proto_msgTypes,
	}.Build()
	File_app_upload_service_proto = out.File
	file_app_upload_service_proto_rawDesc = nil
	file_app_upload_service_proto_goTypes = nil
	file_app_upload_service_proto_depIdxs = nil
}
