// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: app_upload_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*UploadAppRequest_RequestMetaData
	//	*UploadAppRequest_AppInfo
	//	*UploadAppRequest_ChunkData
	Data isUploadAppRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadAppRequest) Reset() {
	*x = UploadAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAppRequest) ProtoMessage() {}

func (x *UploadAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAppRequest.ProtoReflect.Descriptor instead.
func (*UploadAppRequest) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{0}
}

func (m *UploadAppRequest) GetData() isUploadAppRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadAppRequest) GetRequestMetaData() *UploadAppRequestInfo {
	if x, ok := x.GetData().(*UploadAppRequest_RequestMetaData); ok {
		return x.RequestMetaData
	}
	return nil
}

func (x *UploadAppRequest) GetAppInfo() *AppInfo {
	if x, ok := x.GetData().(*UploadAppRequest_AppInfo); ok {
		return x.AppInfo
	}
	return nil
}

func (x *UploadAppRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*UploadAppRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isUploadAppRequest_Data interface {
	isUploadAppRequest_Data()
}

type UploadAppRequest_RequestMetaData struct {
	RequestMetaData *UploadAppRequestInfo `protobuf:"bytes,1,opt,name=request_meta_data,json=requestMetaData,proto3,oneof"`
}

type UploadAppRequest_AppInfo struct {
	AppInfo *AppInfo `protobuf:"bytes,2,opt,name=app_info,json=appInfo,proto3,oneof"`
}

type UploadAppRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadAppRequest_RequestMetaData) isUploadAppRequest_Data() {}

func (*UploadAppRequest_AppInfo) isUploadAppRequest_Data() {}

func (*UploadAppRequest_ChunkData) isUploadAppRequest_Data() {}

type UploadAppRequestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AppSize     string `protobuf:"bytes,2,opt,name=app_size,json=appSize,proto3" json:"app_size,omitempty"`
	FileType    string `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
}

func (x *UploadAppRequestInfo) Reset() {
	*x = UploadAppRequestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAppRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAppRequestInfo) ProtoMessage() {}

func (x *UploadAppRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAppRequestInfo.ProtoReflect.Descriptor instead.
func (*UploadAppRequestInfo) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAppRequestInfo) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UploadAppRequestInfo) GetAppSize() string {
	if x != nil {
		return x.AppSize
	}
	return ""
}

func (x *UploadAppRequestInfo) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type AppInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppMetadata       *AppInfo_AppMetaData       `protobuf:"bytes,1,opt,name=app_metadata,json=appMetadata,proto3" json:"app_metadata,omitempty"`
	Price             *AppInfo_Price             `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	PrivacyCompliance *AppInfo_PrivacyCompliance `protobuf:"bytes,3,opt,name=privacy_compliance,json=privacyCompliance,proto3" json:"privacy_compliance,omitempty"`
	Releases          *AppInfo_Releases          `protobuf:"bytes,4,opt,name=releases,proto3" json:"releases,omitempty"`
	Website           string                     `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{2}
}

func (x *AppInfo) GetAppMetadata() *AppInfo_AppMetaData {
	if x != nil {
		return x.AppMetadata
	}
	return nil
}

func (x *AppInfo) GetPrice() *AppInfo_Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *AppInfo) GetPrivacyCompliance() *AppInfo_PrivacyCompliance {
	if x != nil {
		return x.PrivacyCompliance
	}
	return nil
}

func (x *AppInfo) GetReleases() *AppInfo_Releases {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *AppInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type UploadAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string  `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size float32 `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *UploadAppResponse) Reset() {
	*x = UploadAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAppResponse) ProtoMessage() {}

func (x *UploadAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAppResponse.ProtoReflect.Descriptor instead.
func (*UploadAppResponse) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{3}
}

func (x *UploadAppResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadAppResponse) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AppInfo_AppMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName        string                              `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppIcon        string                              `protobuf:"bytes,2,opt,name=app_icon,json=appIcon,proto3" json:"app_icon,omitempty"`
	AppSubCategory string                              `protobuf:"bytes,3,opt,name=app_sub_category,json=appSubCategory,proto3" json:"app_sub_category,omitempty"`
	AppUrl         string                              `protobuf:"bytes,4,opt,name=app_url,json=appUrl,proto3" json:"app_url,omitempty"`
	AppDescription *AppInfo_AppMetaData_AppDescription `protobuf:"bytes,5,opt,name=app_description,json=appDescription,proto3" json:"app_description,omitempty"`
}

func (x *AppInfo_AppMetaData) Reset() {
	*x = AppInfo_AppMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo_AppMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo_AppMetaData) ProtoMessage() {}

func (x *AppInfo_AppMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo_AppMetaData.ProtoReflect.Descriptor instead.
func (*AppInfo_AppMetaData) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AppInfo_AppMetaData) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppInfo_AppMetaData) GetAppIcon() string {
	if x != nil {
		return x.AppIcon
	}
	return ""
}

func (x *AppInfo_AppMetaData) GetAppSubCategory() string {
	if x != nil {
		return x.AppSubCategory
	}
	return ""
}

func (x *AppInfo_AppMetaData) GetAppUrl() string {
	if x != nil {
		return x.AppUrl
	}
	return ""
}

func (x *AppInfo_AppMetaData) GetAppDescription() *AppInfo_AppMetaData_AppDescription {
	if x != nil {
		return x.AppDescription
	}
	return nil
}

type AppInfo_Price struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AppInfo_Price) Reset() {
	*x = AppInfo_Price{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo_Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo_Price) ProtoMessage() {}

func (x *AppInfo_Price) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo_Price.ProtoReflect.Descriptor instead.
func (*AppInfo_Price) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{2, 1}
}

func (x *AppInfo_Price) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AppInfo_Price) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AppInfo_PrivacyCompliance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions      []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PrivacyPolicyUrl string   `protobuf:"bytes,2,opt,name=privacy_policy_url,json=privacyPolicyUrl,proto3" json:"privacy_policy_url,omitempty"`
}

func (x *AppInfo_PrivacyCompliance) Reset() {
	*x = AppInfo_PrivacyCompliance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo_PrivacyCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo_PrivacyCompliance) ProtoMessage() {}

func (x *AppInfo_PrivacyCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo_PrivacyCompliance.ProtoReflect.Descriptor instead.
func (*AppInfo_PrivacyCompliance) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{2, 2}
}

func (x *AppInfo_PrivacyCompliance) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AppInfo_PrivacyCompliance) GetPrivacyPolicyUrl() string {
	if x != nil {
		return x.PrivacyPolicyUrl
	}
	return ""
}

type AppInfo_Releases struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	GroupId string `protobuf:"bytes,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *AppInfo_Releases) Reset() {
	*x = AppInfo_Releases{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo_Releases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo_Releases) ProtoMessage() {}

func (x *AppInfo_Releases) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo_Releases.ProtoReflect.Descriptor instead.
func (*AppInfo_Releases) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{2, 3}
}

func (x *AppInfo_Releases) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *AppInfo_Releases) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AppInfo_Releases) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type AppInfo_AppMetaData_AppDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongBuildDescription  string `protobuf:"bytes,1,opt,name=long_build_description,json=longBuildDescription,proto3" json:"long_build_description,omitempty"`
	ShortBuildDescription string `protobuf:"bytes,2,opt,name=short_build_description,json=shortBuildDescription,proto3" json:"short_build_description,omitempty"`
}

func (x *AppInfo_AppMetaData_AppDescription) Reset() {
	*x = AppInfo_AppMetaData_AppDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_upload_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppInfo_AppMetaData_AppDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo_AppMetaData_AppDescription) ProtoMessage() {}

func (x *AppInfo_AppMetaData_AppDescription) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo_AppMetaData_AppDescription.ProtoReflect.Descriptor instead.
func (*AppInfo_AppMetaData_AppDescription) Descriptor() ([]byte, []int) {
	return file_app_upload_service_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *AppInfo_AppMetaData_AppDescription) GetLongBuildDescription() string {
	if x != nil {
		return x.LongBuildDescription
	}
	return ""
}

func (x *AppInfo_AppMetaData_AppDescription) GetShortBuildDescription() string {
	if x != nil {
		return x.ShortBuildDescription
	}
	return ""
}

var File_app_upload_service_proto protoreflect.FileDescriptor

var file_app_upload_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x66, 0x65, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xc9, 0x01, 0x0a,
	0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x54, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x66,
	0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x65, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x41, 0x70, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x07, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x71, 0x0a, 0x14, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9b, 0x07, 0x0a, 0x07,
	0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x48, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x5f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x35, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x12, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70,
	0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x11, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x1a, 0xe5,
	0x02, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70,
	0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70,
	0x49, 0x63, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x75, 0x62, 0x5f,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x61, 0x70, 0x70, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x17,
	0x0a, 0x07, 0x61, 0x70, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x5d, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x34, 0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x61, 0x70, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x7e, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x16, 0x6c, 0x6f, 0x6e, 0x67,
	0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x6c, 0x6f, 0x6e, 0x67, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36,
	0x0a, 0x17, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x15, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x31, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x63, 0x0a, 0x11, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x5f, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x55, 0x72, 0x6c, 0x1a, 0x59,
	0x0a, 0x08, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x11, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x32, 0x63, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x56, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x12, 0x22,
	0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x65, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_upload_service_proto_rawDescOnce sync.Once
	file_app_upload_service_proto_rawDescData = file_app_upload_service_proto_rawDesc
)

func file_app_upload_service_proto_rawDescGZIP() []byte {
	file_app_upload_service_proto_rawDescOnce.Do(func() {
		file_app_upload_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_upload_service_proto_rawDescData)
	})
	return file_app_upload_service_proto_rawDescData
}

var file_app_upload_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_upload_service_proto_goTypes = []interface{}{
	(*UploadAppRequest)(nil),                   // 0: feblic.appupload.UploadAppRequest
	(*UploadAppRequestInfo)(nil),               // 1: feblic.appupload.UploadAppRequestInfo
	(*AppInfo)(nil),                            // 2: feblic.appupload.AppInfo
	(*UploadAppResponse)(nil),                  // 3: feblic.appupload.UploadAppResponse
	(*AppInfo_AppMetaData)(nil),                // 4: feblic.appupload.AppInfo.AppMetaData
	(*AppInfo_Price)(nil),                      // 5: feblic.appupload.AppInfo.Price
	(*AppInfo_PrivacyCompliance)(nil),          // 6: feblic.appupload.AppInfo.PrivacyCompliance
	(*AppInfo_Releases)(nil),                   // 7: feblic.appupload.AppInfo.Releases
	(*AppInfo_AppMetaData_AppDescription)(nil), // 8: feblic.appupload.AppInfo.AppMetaData.AppDescription
}
var file_app_upload_service_proto_depIdxs = []int32{
	1, // 0: feblic.appupload.UploadAppRequest.request_meta_data:type_name -> feblic.appupload.UploadAppRequestInfo
	2, // 1: feblic.appupload.UploadAppRequest.app_info:type_name -> feblic.appupload.AppInfo
	4, // 2: feblic.appupload.AppInfo.app_metadata:type_name -> feblic.appupload.AppInfo.AppMetaData
	5, // 3: feblic.appupload.AppInfo.price:type_name -> feblic.appupload.AppInfo.Price
	6, // 4: feblic.appupload.AppInfo.privacy_compliance:type_name -> feblic.appupload.AppInfo.PrivacyCompliance
	7, // 5: feblic.appupload.AppInfo.releases:type_name -> feblic.appupload.AppInfo.Releases
	8, // 6: feblic.appupload.AppInfo.AppMetaData.app_description:type_name -> feblic.appupload.AppInfo.AppMetaData.AppDescription
	0, // 7: feblic.appupload.AppUpload.UploadApp:input_type -> feblic.appupload.UploadAppRequest
	3, // 8: feblic.appupload.AppUpload.UploadApp:output_type -> feblic.appupload.UploadAppResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_app_upload_service_proto_init() }
func file_app_upload_service_proto_init() {
	if File_app_upload_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_upload_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadAppRequestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo_AppMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo_Price); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo_PrivacyCompliance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo_Releases); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_upload_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppInfo_AppMetaData_AppDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_upload_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UploadAppRequest_RequestMetaData)(nil),
		(*UploadAppRequest_AppInfo)(nil),
		(*UploadAppRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_upload_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_upload_service_proto_goTypes,
		DependencyIndexes: file_app_upload_service_proto_depIdxs,
		MessageInfos:      file_app_upload_service_proto_msgTypes,
	}.Build()
	File_app_upload_service_proto = out.File
	file_app_upload_service_proto_rawDesc = nil
	file_app_upload_service_proto_goTypes = nil
	file_app_upload_service_proto_depIdxs = nil
}
